name: example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  auto_route:
    path: ../../auto_route
  modal_bottom_sheet: ^2.0.0


dev_dependencies:
  build_runner:
  json_serializable: ^5.0.0
  flutter_test:
    sdk: flutter
  auto_route_generator:
    path: ../../auto_route_generator
  effective_dart: ^1.3.2

dependency_overrides:
  meta: 1.7.0
#  analyzer: 1.5.0

flutter:
  uses-material-design: true

