name: example
description: A new Flutter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  auto_route:


  collection: any
dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  auto_route_generator:
    path: ../../auto_route_generator
  flutter_lints: ^6.0.0

dependency_overrides:
  auto_route:
    path: ../../auto_route

flutter:
  uses-material-design: true
