name: example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  auto_route:
    path: ../../auto_route


dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  auto_route_generator:
    path: ../../auto_route_generator
  effective_dart: ^1.3.2


flutter:
  uses-material-design: true

